# sample.R
#
# A minimal analysis script, shipped with submitr as something to point a
# first job at. It has no data dependency, so it runs anywhere, but it
# follows the conventions a real analysis should: everything it produces
# goes into output/, using a relative path.
#
# That relative path is the important part. It resolves to the project
# folder in RStudio and to HTCondor's scratch directory on an execute node,
# because the executable script generated by htc_gen_executable() moves
# there before calling Rscript. The script itself never has to know where
# it is running, and htc_gen_executable() archives output/ into the
# results tarball that comes home.

set.seed(42)

n     <- 500
steps <- sample(c(-1, 1), n, replace = TRUE)
walk  <- cumsum(steps)

summary_stats <- data.frame(
    final_position     = tail(walk, 1),
    highest_point      = max(walk),
    lowest_point       = min(walk),
    times_crossed_zero = sum(walk == 0)
)

print(summary_stats)

# Only output/ itself is created by the generated executable script. A
# script writing to a subfolder such as output/figures/ has to create it,
# which is what recursive = TRUE is for here.
output_dir <- "output"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

write.csv(
    summary_stats,
    file.path(output_dir, "summary.csv"),
    row.names = FALSE
)

png(file.path(output_dir, "walk.png"), width = 900, height = 500)

plot(
    walk,
    type = "l",
    lwd  = 2,
    main = "A random walk in base R",
    xlab = "Step",
    ylab = "Position"
)

abline(h = 0, lty = 2)
points(which.max(walk), max(walk), pch = 19)
points(which.min(walk), min(walk), pch = 19)

dev.off()
